language: php

php:
  - 7
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - DEPS=lowest
  - DEPS=highest

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  - if [ "$DEPS" = "lowest" ]; then
      travis_retry composer update --no-interaction --prefer-source --prefer-lowest;
    else
      travis_retry composer update --no-interaction --prefer-source;
    fi;
  - composer show

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - $HOME/.composer/cache
